version: "2"
services:
  app:
    extends:
      file: ../docker-compose-common.yml
      service: app
    command: make start
    ports:
      - "3000:3000"
    volumes:
      - ../../app/src:/home/app/app/src
      - ../../app/public:/home/app/app/public
      - ../../app/package.json:/home/app/app/package.json
      - ../../app/yarn.lock:/home/app/app/yarn.lock
      - ../../app/.env:/home/app/app/.env
      - ../../app/Makefile:/home/app/app/Makefile
      - ../../app/.prettierrc:/home/app/app/.prettierrc
      - ../../app/.eslintrc.yml:/home/app/app/.eslintrc.yml
      - ../../app/webapp.conf:/etc/nginx/sites-enabled/webapp.conf
