version: "2"
services:
  cca:
    extends:
      file: ../docker-compose-common.yml
      service: cca
    command: make start
    ports:
      - "3000:3000"
    volumes:
      - ../../cca/src:/home/app/cca/src
      - ../../cca/public:/home/app/cca/public
      - ../../cca/package.json:/home/app/cca/package.json
      - ../../cca/yarn.lock:/home/app/cca/yarn.lock
      - ../../cca/.env:/home/app/cca/.env
      - ../../cca/Makefile:/home/app/cca/Makefile
      - ../../cca/.prettierrc:/home/app/cca/.prettierrc
      - ../../cca/.eslintrc.yml:/home/app/cca/.eslintrc.yml
      - ../../cca/webapp.conf:/etc/nginx/sites-enabled/webapp.conf
